# Generated by Django 6.0 on 2026-01-12 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=130)),
                ('favicon', models.ImageField(upload_to='static/uploads/')),
                ('logo', models.ImageField(upload_to='static/uploads/')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(9)])),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
                ('linkedin_link', models.URLField(blank=True)),
            ],
        ),
    ]
