# Generated by Django 6.0 on 2026-02-22 08:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_category_user_product_user'),
        ('userpage', '0002_cart'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('address', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(10)])),
                ('payment_method', models.CharField(choices=[('COD', 'COD'), ('Card', 'Card')], max_length=20)),
                ('payment_status', models.CharField(default=False, null=True)),
                ('order_status', models.CharField(choices=[('In Progress', 'In Progress'), ('way to deliver', 'way to deliver'), ('Complete', 'complete')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
