# Generated by Django 6.0 on 2026-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('way to deliver', 'way to deliver'), ('Complete', 'complete')], default='In Progress', max_length=20),
        ),
    ]
